name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_NAME: my-image-name
      run: |
        docker buildx create --use
        docker buildx inspect default --bootstrap
        docker buildx build --file Dockerfile --tag $IMAGE_NAME:$(date +%s) --output type=image,registry=${{ secrets.DOCKER_REGISTRY }} --platform linux/amd64 .

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image
      env:
        IMAGE_NAME: my-image-name
      run: |
        docker push $IMAGE_NAME:$(date +%s)

