name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker buildx create --use
        docker buildx inspect default --bootstrap
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker buildx build --file TesteAccenture/Dockerfile --tag wowtzcantfly/testeaccenture:v1 --output type=image,registry=${{ secrets.DOCKER_REGISTRY }} --platform linux/amd64 .
        docker tag wowtzcantfly/testeaccenture:v1 wowtzcantfly/testeaccenture:v1
    - name: Push Docker image
      run: |
        docker tag wowtzcantfly/testeaccenture:v1 wowtzcantfly/testeaccenture:v1
        docker push wowtzcantfly/testeaccenture:v1
